-- MySQL Script generated by MySQL Workbench
-- Sat Jul 14 17:03:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_examhelper
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_examhelper` ;

-- -----------------------------------------------------
-- Schema db_examhelper
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_examhelper` DEFAULT CHARACTER SET utf8 ;
USE `db_examhelper` ;

-- -----------------------------------------------------
-- Table `db_examhelper`.`certificate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_examhelper`.`certificate` ;

CREATE TABLE IF NOT EXISTS `db_examhelper`.`certificate` (
  `cer_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `grade` VARCHAR(200) NULL,
  PRIMARY KEY (`cer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_examhelper`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_examhelper`.`user` ;

CREATE TABLE IF NOT EXISTS `db_examhelper`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(200) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `role` INT NOT NULL DEFAULT 0,
  `token` VARCHAR(300) NULL,
  `create_date` DATETIME NOT NULL,
  `status` INT NULL,
  `wechar_openid` VARCHAR(200) NULL,
  `qq_number` VARCHAR(200) NULL,
  `qq_openid` VARCHAR(200) NULL,
  `cer_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_certificate1_idx` (`cer_id` ASC),
  CONSTRAINT `fk_user_certificate1`
    FOREIGN KEY (`cer_id`)
    REFERENCES `db_examhelper`.`certificate` (`cer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_examhelper`.`property`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_examhelper`.`property` ;

CREATE TABLE IF NOT EXISTS `db_examhelper`.`property` (
  `pro_id` INT NOT NULL AUTO_INCREMENT,
  `chapter` VARCHAR(200) NOT NULL,
  `time` DATETIME NOT NULL,
  PRIMARY KEY (`pro_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_examhelper`.`synthesize`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_examhelper`.`synthesize` ;

CREATE TABLE IF NOT EXISTS `db_examhelper`.`synthesize` (
  `syn_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `select` VARCHAR(2000) NOT NULL,
  `result` INT NULL,
  `analysis` VARCHAR(200) NULL,
  `pro_id` INT NOT NULL,
  `cer_id` INT NOT NULL,
  PRIMARY KEY (`syn_id`),
  INDEX `fk_synthesize_property1_idx` (`pro_id` ASC),
  INDEX `fk_synthesize_certificate1_idx` (`cer_id` ASC),
  CONSTRAINT `fk_synthesize_property1`
    FOREIGN KEY (`pro_id`)
    REFERENCES `db_examhelper`.`property` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_synthesize_certificate1`
    FOREIGN KEY (`cer_id`)
    REFERENCES `db_examhelper`.`certificate` (`cer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_examhelper`.`case`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_examhelper`.`case` ;

CREATE TABLE IF NOT EXISTS `db_examhelper`.`case` (
  `case_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `content` VARCHAR(2000) NOT NULL,
  `img` VARCHAR(2000) NULL,
  `result` VARCHAR(2000) NULL,
  `pro_id` INT NOT NULL,
  `cer_id` INT NOT NULL,
  PRIMARY KEY (`case_id`),
  INDEX `fk_case_property1_idx` (`pro_id` ASC),
  INDEX `fk_case_certificate1_idx` (`cer_id` ASC),
  CONSTRAINT `fk_case_property1`
    FOREIGN KEY (`pro_id`)
    REFERENCES `db_examhelper`.`property` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_case_certificate1`
    FOREIGN KEY (`cer_id`)
    REFERENCES `db_examhelper`.`certificate` (`cer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_examhelper`.`thesis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_examhelper`.`thesis` ;

CREATE TABLE IF NOT EXISTS `db_examhelper`.`thesis` (
  `thesis_id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(2000) NULL,
  `pro_id` INT NOT NULL,
  `cer_id` INT NOT NULL,
  PRIMARY KEY (`thesis_id`),
  INDEX `fk_thesis_property1_idx` (`pro_id` ASC),
  INDEX `fk_thesis_certificate1_idx` (`cer_id` ASC),
  CONSTRAINT `fk_thesis_property1`
    FOREIGN KEY (`pro_id`)
    REFERENCES `db_examhelper`.`property` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_thesis_certificate1`
    FOREIGN KEY (`cer_id`)
    REFERENCES `db_examhelper`.`certificate` (`cer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO user1;
 DROP USER user1;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'user1';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
